#!/bin/bash
timestamp="$(date +%d.%m.%Y"-"%H:%M:%S)"
XDG_PICTURES_DIR=${XDG_PICTURES_DIR:-$HOME/pictures}
targetbase="$XDG_PICTURES_DIR/screenshots"
USAGE=

mkdir -p $targetbase
[ -d $targetbase ] || exit 1
case "$1" in
	"all")
		import -window root $targetbase/$timestamp.png
		exit 0
		;;
	"window")
		import -window "$(xdotool getwindowfocus -f)" $targetbase/$timestamp.png
		exit 0
		;;
	"frame")
		import -frame $targetbase/$timestamp.png
		exit 0
		;;
	"help"|"-h"|"--help")
		cat <<-EndHelp
			Usage: capscr all|window|frame

			Actions:
			    all            For capturing the whole screen
			    window         For capturing the current screen only (uses xdotool)
			    frame          For capturing a frame with the mouse
			    help|-h|--help      For showing this help message
		EndHelp
		exit 0
		;;
	*)
		cat <<-EndUsage
			Usage: capscr all|window|frame
			Try 'capscr help' for more information.
		EndUsage
		exit 1
		;;
esac
