#!/bin/bash
timestamp="$(date +%d.%m.%Y"-"%H:%M:%S)"
targetbase="$XDG_PICTURES_DIR/screenshots"
mkdir -p $targetbase
[ -d $targetbase ] || exit 1
case "$1" in
	"all")
		import -window root $targetbase/$timestamp.png
		;;
	"window")
		import -window "$(xdotool getwindowfocus -f)" $targetbase/$timestamp.png
		;;
	"frame")
		import -frame $targetbase/$timestamp.png
		;;
	*)
		echo please specify a valid option
		;;
esac
