#!/bin/sh

# Wrap firefox such that it won't launch when time is not synchronized - use
# timedatectl to check that. If time is not synchronized when firefox is
# launched, the cookies will be destroyed and it requires logging in to all
# websites to get new cookies.
#
# Ignore SIGPIPE. Writes to closed std{out,err} pipes will now fail silently
# instead of terminating the script instantly - from some reason this is the
# case when Neovim calls this script via `system()`.
trap '' PIPE

{
	IFS= read -r _
	IFS= read -r firefox
} <<EOF
$(which -a firefox)
EOF

echo Checking NTP synchronization
if [ "$(timedatectl show --property=NTPSynchronized --value)" = "yes" ]; then
	"$firefox" "$@"
else
	while true; do
		msg="Waiting for Network Time Sync..."
		echo "$msg"
		(
			while true; do
				if [ "$(timedatectl show --property=NTPSynchronized --value)" = "yes" ]; then
					echo 100
					break
				fi
				echo 0
				sleep 0.4
			done
		) | zenity --progress \
			--pulsate \
			--auto-close \
			--width=500 \
			--title="Firefox NTP Cookies Safety Wrapper" \
			--text="$msg"
		"$firefox" "$@"
	done
fi
