#!/bin/sh

{
    IFS= read -r _
    IFS= read -r git
} <<EOF
$(which -a git)
EOF

if on_network_with_ssh; then
	exec "$git" \
		-c url."ssh://git@github.com/".pushInsteadOf="https://github.com/" \
		-c url."ssh://git@github.com/".pushInsteadOf="gh:" \
		-c url."ssh://git@gitlab.com/".pushInsteadOf="https://gitlab.com/" \
		-c url."ssh://git@github.com/".pushInsteadOf="gh:" \
		"$@"
else
	exec "$git" "$@"
fi
