#!/bin/zsh
# A script to reload all dotfiles in the correct order. use `bash` or `zsh`
# as an argument. It must be used with an alias defined in ~/.zprofile like that:
# `alias load=". ~/.bin/load"` - otherwise the script won't really load your files.

# /etc/zsh/zshenv is loaded in /etc/profile to get the function called:
# `add2PATH-only-if-arg-not-exist`
source /etc/profile
if [ "$1" = "zsh" ]; then
	if [ -d /etc/zsh ]; then
		source /etc/zsh/zprofile
		source /etc/zsh/zshrc
		source /etc/zsh/zlogin
	else
		echo "you don't seem to have zsh installed at all"
	fi
fi
if [ -f "$HOME/.profile" ]; then
	source "$HOME/.profile"
fi
if [ -f "$HOME/.zshenv" ]; then
	source "$HOME/.zshenv"
fi
if [ -f "$HOME/.zlogin" ]; then
	source "$HOME/.zlogin"
fi
if [ -f "$HOME/.zprofile" ]; then
	source "$HOME/.zprofile"
fi
if [ "$1" = "bash" ]; then
	source ~/.bashrc
elif [ "$1" = "zsh" ]; then
	source ~/.zshrc
fi
