#!/bin/sh
# volume for when there is no last volume set.
#DEFAULT_VOLUME=15
if [ "$(mpc | grep volume | sed -e 's/\(volume\|repeat\|random\|single\|consume\|off\|on\|:\|%\|\s\)//g')" -eq "0" ]; then
	echo volume is zero
	echo volume will be set to "$MPC_LAST_VOLUME"
	mpc volume "$(cat /tmp/mpc-mute-toggle.last-volume)"
else
	echo volume is not zero
	mpc | grep volume | sed -e 's/\(volume\|repeat\|random\|single\|consume\|off\|on\|:\|%\|\s\)//g' > /tmp/mpc-mute-toggle.last-volume
	mpc volume 0
fi
