#!/bin/sh
# volume for when there is no last volume set.
#DEFAULT_VOLUME=15
if [ "$(mpc volume)" == "volume:  0%" ]; then
	echo volume is zero
	mpc volume $(cat /tmp/mpc-toggle-mute.last-volume)
else
	echo volume is not zero
	mpc volume | awk -F':' '{gsub(/%/,"",$2); print $2}' > /tmp/mpc-toggle-mute.last-volume
	mpc volume 0
fi
