#!/usr/bin/env zsh

basename="$(basename $0)"

source_dir="$1"
shift
f="$(print -lr -- "$source_dir"/*(om[1]))"
cmd=${basename%l}
case $cmd in
	mv)
		printf "mvl (moving)"
		;;
	cp)
		printf "cpl (copying)"
		;;
esac
echo " this: $f $@"

$cmd $f "$@"
