#!/bin/sh

{
    IFS= read -r _
    IFS= read -r nix
} <<EOF
$(which -a nix)
EOF

# We disable the `--option` when doing completion - from some reason it cause
# the completion function to just complete `--option` unconditionally.
if ! on_network_with_ssh || [ "$NIX_GET_COMPLETIONS" != "" ]; then
	exec "$nix" "$@"
else
	exec "$nix" \
		--option builders "@$HOME/.config/nix/builders.txt" \
		"$@"
fi
