#!/bin/sh

# nixos-rebuild wrapper
if [[ "$1" == "ZENIX" || "$1" == "office" ]]; then
	h="$1"
	shift 1
fi
if [[ "$1" == -u ]]; then
	cd $HOME/repos/nixos-configs
	nix flake update --commit-lock-file
	cd ~-
	shift 1
fi
orig_home=$HOME
if [[ "$1" == boot || "$1" == switch ]]; then
	alias nixos-rebuild='sudo nixos-rebuild'
fi
if type nom &> /dev/null ; then
	nixos-rebuild \
		--flake $orig_home/repos/nixos-configs#$h \
		--keep-going \
		"$@" |& nom
else
	nixos-rebuild \
		--flake $orig_home/repos/nixos-configs#$h \
		--keep-going \
		"$@"
fi
