#!/bin/sh

{
	IFS= read -r _
	IFS= read -r nixos_rebuild
} <<EOF
$(which -a nixos-rebuild)
EOF

# See also https://github.com/NixOS/nix/issues/7154#issuecomment-1975851354 for
# NIX_REMOTE env...
if on_network_with_ssh; then
	exec env \
		NIX_CONFIG="$NIX_CONFIG" \
		NIX_REMOTE=daemon \
		"$nixos_rebuild" \
		--option builders "@$HOME/.config/nix/builders.txt" \
		"$@"
else
	exec env \
		NIX_CONFIG="$NIX_CONFIG" \
		NIX_REMOTE=daemon \
		"$nixos_rebuild" \
		"$@"
fi
