#!/bin/sh

# {{{1 `_command_exists`: Show if a command exists
# Taken from http://stackoverflow.com/a/592649/4935114
_command_exists () {
	type "$1" &> /dev/null ;
}

if [ -f ~/.disable-net-ssh-check ] || ! _command_exists nmcli; then
	exit 0
fi
# SSH_PROBLEMATIC_NETWORK_UUID is defined in ~/.local/share/zsh/env/$HOST
if nmcli connection show --active | grep -q "$SSH_PROBLEMATIC_NETWORK_UUID"; then
	exit 1
fi
# The default behavior is to assume ssh is available
exit 0
