#!/bin/sh
# TAKEN FROM https://unix.stackexchange.com/a/236747/135796
# choose pinentry depending on PINENTRY_USER_DATA
# requires pinentry-curses and pinentry-gtk2
# this *only works* with gpg 2
# see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=802020

case $PINENTRY_USER_DATA in
	"")
		case "$XDG_SESSION_DESKTOP" in
			"")
				exec pinentry-tty "$@"
				;;
			gnome*)
				exec pinentry-gnome3 "$@"
				;;
			*)
				exec pinentry-gtk-2 "$@"
				;;
		esac
		;;
	curses|emacs|gnome3|gtk-2|qt|tty)
		exec pinentry-${PINENTRY_USER_DATA} "$@"
		;;
	*)
		echo there is no such pinentry program: pinentry-"${PINENTRY_USER_DATA}" >&2
		exit 1
esac
