#!/bin/sh
# TAKEN FROM https://unix.stackexchange.com/a/236747/135796
# choose pinentry depending on PINENTRY_USER_DATA
# requires pinentry-curses and pinentry-gtk2
# this *only works* with gpg 2
# see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=802020

case $PINENTRY_USER_DATA in
	"")
		exec /usr/bin/pinentry "$@"
		;;
	curses|emacs|gnome3|gtk-2|qt|tty)
		exec /usr/bin/pinentry-${PINENTRY_USER_DATA} "$@"
		;;
	*)
		echo there is no such pinentry program: /usr/bin/pinentry-"${PINENTRY_USER_DATA}" >&2
		exit 1
esac
