#!/bin/bash
timestamp="$(date +%d.%m.%Y"-"%H:%M:%S)"
targetbase="$HOME/videos/screencasts"
mkdir -p $targetbase
# Exit if creating the folder was not successful:
[ -d $targetbase ] || exit 1

# If screen-casting is already running
if [ -f /tmp/doron-is-screencasting ]; then
	kill `ps aux | grep -v grep | grep ffmpeg | awk '{ print $2 }'`
	rm /tmp/doron-is-screencasting
else
	touch /tmp/doron-is-screencasting
	case "$1" in
		"--with-sound")
			ffmpeg -f x11grab -video_size 1680x1080 -framerate 30 -i $DISPLAY -f pulse -ac 2 -i default $targetbase/$timestamp.mp4 &
			;;
		*)
			ffmpeg -f x11grab -video_size 1680x1080 -framerate 30 -i $DISPLAY $targetbase/$timestamp.mp4 &
			;;
	esac
fi
