#!/bin/bash
IFS=$'\n'
while read -r line; do
	if [ "$1" = "$(echo "$line" | cut -d',' -f1)" ]; then
		eval cd "$(echo "$line" | cut -d',' -f2)"
		if [ -f makefile ]; then
			grep '=' makefile | grep -v '\$' | while read -r l; do
				export $l
			done
			ls -lh
			git status
		fi
	fi
done < ~/.sh/enviorments.csv
IFS=$OLDIFS
