#!/usr/bin/perl

my $blanked = 0;
open (IN, "xscreensaver-command -watch |");
while (<IN>) {
    if (m/^(BLANK|LOCK)/) {
        if (!$blanked) {
            system "ssh-add -D; gpg-connect-agent reloadagent /bye";
            $blanked = 1;
        }
    } elsif (m/^UNBLANK/) {
        $blanked = 0;
    }
}
