#!/bin/bash
# quartus IDE command line interface:
quartus(){
	if [ "$1" = "gui" ] || [ "$1" = "--gui" ] || [ "$1" = "-g" ]; then
		command $QUARTUS_BIN/quartus --64bit "${@:2}" > /dev/null 2>&1 &
	elif [ "$1" = "" ]; then
		echo "Usage:\n--gui | -g | gui for the gui version or:"
		echo `ls $QUARTUS_BIN/quartus_* | cut -d'_' -f2`;
	else
		IFS=$'\n'
		for EXTENSION in $(ls $QUARTUS_BIN/quartus_* | cut -d'_' -f2); do
			if [ "$1" = "$EXTENSION" ]; then
				command $QUARTUS_BIN/quartus_$EXTENSION --64bit "${@:2}"
			fi
		done
		IFS=$OLDIFS
	fi
}

'='(){
	awk "BEGIN{ print $* }"
}
# open vim enviorments easily with a database csv file in ~/.shell/vim-enviorments
# store your database in the following format:
# name,source # a line must
# project1,~/repos/project1/.vim-source-file
# project2,~/repos/project2/.vim-source-file
v(){
	IFS=$'\n'
	for i in `cat ~/.shell/vim-enviorments | cut -d',' -f1`; do
		if [ "$i" = "$1" ]; then
			vim -S $(grep "$i" ~/.shell/vim-enviorments | cut -d',' -f2)
		fi
	done
	IFS=$OLDIFS
}
# vim:syn=sh
