#!/bin/sh

if ! _command_exists gpg; then
	return
fi

# Control what pinentry program is going to be used, using the wrapper at ~/.bin/pinentry
if tty -s; then
	if _command_exists pinentry-curses; then
		PINENTRY_USER_DATA="curses"
	elif _command_exists pinentry-tty; then
		PINENTRY_USER_DATA="tty"
	else
		PINENTRY_USER_DATA=""
	fi
fi
