#!/bin/zsh

# {{{1 `fpath` list of paths for directories containing functions for zsh completion
fpath(){
	echo "$fpath" | sed -e 's/\ /\n/g'
}

# {{{1 `zrc` reload zsh completion for a given command
zrc(){
	if [[ ! -z "$1" ]]; then
		unfunction "_$1"
		autoload "_$1" && return 0
	else
		echo please use this command with an argument >&2
		return 1
	fi
}
